/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/
public class problem2 {
    public static void main(String[] args) {
        int sum = 0;
        boolean under = true;
        int i = 1;
        int j = 2;
        while(under){
            if(j%2 == 0){
                sum = sum + j;
            }
            int temp = i + j;
            i = j;
            j = temp;
            if(temp >= 4000000){
                under = false;
            }
        }
        System.out.println(sum);
    }
}